import { useEffect, useRef, useState } from 'react';
import SvgIcon, { iconNameFromValue } from '../components/SvgIcon.jsx';
import { useNavigate, useParams } from 'react-router-dom';
import { apiAssetUrl, apiDelete, apiGet, apiPost, apiPut, apiUpload } from '../api/appClient.js';
import { useAuth } from '../context/AuthContext.jsx';

const deletionRequest=body=>{const m=String(body||'').match(/^ACCOUNT_DELETE_REQUEST:(\d+)\|(.*)$/s);return m?{requestId:Number(m[1]),text:m[2]}:null;};
const initials=name=>String(name||'?').split(' ').map(x=>x[0]).join('').slice(0,2);
const reportReasons=['Harassment or bullying','Hate speech','Threats or violence','Sexual content','Spam or scam','Impersonation','Other'];

export default function GroupChat(){
  const {id}=useParams(),navigate=useNavigate(),{user,showToast}=useAuth();
  const [group,setGroup]=useState(null),[msgs,setMsgs]=useState([]),[members,setMembers]=useState([]),[body,setBody]=useState(''),[dmTo,setDmTo]=useState(null),[tab,setTab]=useState('group');
  const [busy,setBusy]=useState(false),[replyTo,setReplyTo]=useState(null),[menuMessage,setMenuMessage]=useState(null),[recording,setRecording]=useState(false),[historyError,setHistoryError]=useState(''),[memberError,setMemberError]=useState('');
  const [blockedIds,setBlockedIds]=useState([]),[reportTarget,setReportTarget]=useState(null),[reportReason,setReportReason]=useState(reportReasons[0]),[reportDetails,setReportDetails]=useState(''),[moderationBusy,setModerationBusy]=useState(false);
  const endRef=useRef(null),fileRef=useRef(null),pressTimer=useRef(null),recorderRef=useRef(null),recordChunks=useRef([]),streamRef=useRef(null);
  const loadMessages=async()=>{try{const data=await apiGet('/messages/group/'+id);if(Array.isArray(data)){setMsgs(data);setHistoryError('');}}catch(e){setHistoryError(e.message||'Messages could not refresh.');}};
  const loadGroup=async()=>{
    const [groupResult,memberResult]=await Promise.allSettled([apiGet('/groups/'+id),apiGet('/members/'+id)]);
    if(groupResult.status==='fulfilled')setGroup(groupResult.value||null);
    const groupMembers=groupResult.status==='fulfilled'&&Array.isArray(groupResult.value?.members)?groupResult.value.members:[];
    const routeMembers=memberResult.status==='fulfilled'&&Array.isArray(memberResult.value)?memberResult.value:[];
    const available=routeMembers.length?routeMembers:groupMembers;
    if(available.length||memberResult.status==='fulfilled'||groupMembers.length){setMembers(available.filter(x=>x.Status==='Approved'));setMemberError('');}
    else setMemberError('Could not load group members. Pull down or reopen the chat to retry.');
  };
  const loadBlocks=async()=>{try{const data=await apiGet('/messages/blocks');setBlockedIds(Array.isArray(data)?data.map(Number):[]);}catch{/* Messages still remain available if moderation state cannot refresh. */}};
  useEffect(()=>{loadMessages();loadGroup();loadBlocks();const timer=setInterval(loadMessages,5000);return()=>clearInterval(timer);},[id,user?.UserId]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'});},[msgs.length,tab,dmTo?.UserId]);
  useEffect(()=>{document.documentElement.classList.add('chat-page-active');document.body.classList.add('chat-page-active');return()=>{document.documentElement.classList.remove('chat-page-active');document.body.classList.remove('chat-page-active');clearTimeout(pressTimer.current);streamRef.current?.getTracks().forEach(t=>t.stop());};},[]);

  const viewer=members.find(x=>Number(x.UserId)===Number(user?.UserId)),isAdmin=viewer?.Role==='Admin',anonymous=!!group?.GroupMembersAnonymous;
  const pendingIds=new Set(msgs.filter(x=>x.IsPrivate&&Number(x.RecipientId)===Number(user?.UserId)&&deletionRequest(x.Body)).map(x=>Number(x.SenderId)));
  const people=members.filter(x=>Number(x.UserId)!==Number(user?.UserId)&&(!anonymous||isAdmin||x.Role==='Admin')).sort((a,b)=>(pendingIds.has(Number(b.UserId))?1:0)-(pendingIds.has(Number(a.UserId))?1:0));
  const hasAi=msgs.some(x=>x.IsPrivate&&x.SenderNameOverride==='My Ajo AI');
  const privateMembers=hasAi?[{UserId:'myajo-ai',FirstName:'My Ajo',LastName:'AI',IsSystem:true,AvatarColor:'var(--deep)'},...people]:people;
  const shown=tab==='group'?msgs.filter(x=>!x.IsPrivate):dmTo?.IsSystem?msgs.filter(x=>x.IsPrivate&&x.SenderNameOverride==='My Ajo AI'&&Number(x.RecipientId)===Number(user?.UserId)):dmTo?msgs.filter(x=>x.IsPrivate&&(Number(x.SenderId)===Number(user?.UserId)||Number(x.RecipientId)===Number(user?.UserId))&&(Number(x.SenderId)===Number(dmTo.UserId)||Number(x.RecipientId)===Number(dmTo.UserId))):[];

  const conversationFields=()=>({recipientId:tab==='dm'?dmTo?.UserId:null,isPrivate:tab==='dm',replyToMessageId:replyTo?.MessageId||null});
  const afterSend=async()=>{setBody('');setReplyTo(null);await loadMessages();};
  const send=async event=>{event.preventDefault();if(!body.trim())return;setBusy(true);try{await apiPost('/messages/group/'+id,{body,...conversationFields()});await afterSend();}catch(e){showToast(e.message||'Could not send message','error');}finally{setBusy(false);}};
  const uploadFile=async file=>{if(!file)return;setBusy(true);try{const data=new FormData();data.append('attachment',file,file.name);data.append('body',body);Object.entries(conversationFields()).forEach(([k,v])=>{if(v!==null&&v!==undefined)data.append(k,String(v));});await apiUpload('/messages/group/'+id+'/upload',data);await afterSend();}catch(e){showToast(e.message||'Could not upload attachment','error');}finally{setBusy(false);if(fileRef.current)fileRef.current.value='';}};
  const toggleRecording=async()=>{
    if(recording){const recorder=recorderRef.current;if(recorder?.state==='recording'){try{recorder.requestData();}catch{/* unsupported by some WebViews */}recorder.stop();}setRecording(false);return;}
    if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){showToast('Voice recording is not supported on this device.','error');return;}
    try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;recordChunks.current=[];const preferred=['audio/mp4','audio/webm;codecs=opus','audio/webm','audio/ogg'].find(x=>MediaRecorder.isTypeSupported?.(x));const recorder=new MediaRecorder(stream,preferred?{mimeType:preferred}:undefined);recorderRef.current=recorder;recorder.ondataavailable=e=>{if(e.data.size)recordChunks.current.push(e.data);};recorder.onerror=e=>showToast(e.error?.message||'Voice recording failed.','error');recorder.onstop=async()=>{const type=recorder.mimeType||preferred||'audio/webm',ext=type.includes('mp4')?'m4a':type.includes('ogg')?'ogg':'webm';stream.getTracks().forEach(t=>t.stop());setRecording(false);if(!recordChunks.current.length){showToast('No audio was recorded. Please try again.','error');return;}await uploadFile(new File(recordChunks.current,`voice-note-${Date.now()}.${ext}`,{type}));};recorder.start(1000);setRecording(true);showToast('Recording voice note. Tap the red button to stop and send.');}catch(e){streamRef.current?.getTracks().forEach(t=>t.stop());setRecording(false);showToast(e.name==='NotAllowedError'?'Microphone permission was not granted.':e.message||'Could not start recording.','error');}
  };
  const messageAction=async(action,message)=>{setMenuMessage(null);if(action==='reply'){setReplyTo(message);return;}try{if(action==='pin')await apiPut('/messages/'+message.MessageId+'/pin',{pinned:!message.IsPinned});if(action==='delete')await apiDelete('/messages/'+message.MessageId);await loadMessages();}catch(e){showToast(e.message||'Message action failed','error');}};
  const startPress=(event,message)=>{if(event.pointerType==='mouse'&&event.button!==0)return;clearTimeout(pressTimer.current);pressTimer.current=setTimeout(()=>setMenuMessage(message),2000);};
  const cancelPress=()=>clearTimeout(pressTimer.current);
  const respondDeletion=async(requestId,action)=>{try{await apiPost(`/auth/account-deletion-requests/${requestId}/${action}`,{});await loadMessages();showToast(`Deletion request ${action==='accept'?'accepted':'declined'}.`);}catch(e){showToast(e.message||'Could not update deletion request','error');}};
  const openReport=(type,target)=>{setMenuMessage(null);setReportReason(reportReasons[0]);setReportDetails('');setReportTarget({type,target});};
  const submitReport=async event=>{event.preventDefault();if(!reportTarget)return;setModerationBusy(true);try{if(reportTarget.type==='message')await apiPost(`/messages/${reportTarget.target.MessageId}/report`,{reason:reportReason,details:reportDetails});else await apiPost(`/messages/users/${reportTarget.target.UserId}/report`,{groupId:Number(id),reason:reportReason,details:reportDetails});showToast('Report submitted. Our moderation team will review it.');setReportTarget(null);}catch(e){showToast(e.message||'Could not submit report','error');}finally{setModerationBusy(false);}};
  const toggleBlock=async person=>{const userId=Number(person?.UserId??person?.SenderId);if(!userId)return;const blocked=blockedIds.includes(userId),name=person?.FirstName?`${person.FirstName} ${person.LastName}`:person?.SenderName||'this user';if(!blocked&&!window.confirm(`Block ${name}? Their messages will be hidden and private messaging between you will stop.`))return;setMenuMessage(null);setModerationBusy(true);try{if(blocked)await apiDelete(`/messages/users/${userId}/block`);else await apiPost(`/messages/users/${userId}/block`,{groupId:Number(id)});await Promise.all([loadBlocks(),loadMessages()]);if(!blocked&&Number(dmTo?.UserId)===userId)setDmTo(null);showToast(blocked?'User unblocked.':'User blocked.');}catch(e){showToast(e.message||'Could not update blocked users','error');}finally{setModerationBusy(false);}};
  const title=tab==='group'?(group?.GroupName||'Group Chat'):dmTo?`${dmTo.FirstName} ${dmTo.LastName}`:'Private Chat';

  return <div className={`page-enter chat-page ${tab==='dm'&&dmTo?'chat-dm-open':tab==='dm'?'chat-dm-picking':''}`}>
    <header className="chat-app-header"><button onClick={()=>tab==='dm'&&dmTo?setDmTo(null):navigate(`/group/${id}`)} aria-label="Back"><SvgIcon name="arrowLeft" size={22}/></button><span className="chat-title-avatar">{tab==='group'?<SvgIcon name={iconNameFromValue(group?.Icon,'groups')} size={21}/>:dmTo?.ProfilePicture?<img src={apiAssetUrl(dmTo.ProfilePicture)} alt=""/>:initials(title)}</span><div><strong>{title}</strong><small>{tab==='group'?`${members.length} members`:dmTo?'Private message':'Choose a member'}</small></div></header>
    <div className="chat-mode-tabs"><button className={tab==='group'?'active':''} onClick={()=>{setTab('group');setDmTo(null);}}><SvgIcon name="message" size={16}/>Group chat</button><button className={tab==='dm'?'active':''} onClick={()=>{setTab('dm');setDmTo(null);}}><SvgIcon name="user" size={16}/>Private chat</button></div>
    {tab==='dm'&&dmTo&&!dmTo.IsSystem&&<div className="chat-safety-bar"><span><SvgIcon name="shield" size={16}/>Safety</span><button type="button" onClick={()=>openReport('user',dmTo)}>Report user</button><button type="button" className={blockedIds.includes(Number(dmTo.UserId))?'':'danger'} onClick={()=>toggleBlock(dmTo)} disabled={moderationBusy}>{blockedIds.includes(Number(dmTo.UserId))?'Unblock user':'Block user'}</button></div>}
    <div className="chat-shell">
      {tab==='dm'&&!dmTo&&<aside className="chat-contact-list"><h3>Private messages</h3>{memberError&&<div className="chat-sync-warning">{memberError}</div>}{privateMembers.map(x=><button key={x.UserId} onClick={()=>setDmTo(x)}><span className="chat-title-avatar">{x.ProfilePicture?<img src={apiAssetUrl(x.ProfilePicture)} alt=""/>:initials(`${x.FirstName} ${x.LastName}`)}</span><span><strong>{x.FirstName} {x.LastName}</strong><small>{pendingIds.has(Number(x.UserId))?'Deletion request awaiting review':'Open conversation'}</small></span><SvgIcon name="arrowRight" size={17}/></button>)}{!memberError&&!privateMembers.length&&<p>No other approved members are available for private chat.</p>}</aside>}
      {(tab==='group'||dmTo)&&<section className="chat-panel">
        {historyError&&<div className="chat-sync-warning">Offline: showing the last loaded chat history.</div>}
        <div className="chat-messages">{shown.map(m=>{const mine=Number(m.SenderId)===Number(user?.UserId),request=deletionRequest(m.Body),canDelete=mine||isAdmin,blocked=blockedIds.includes(Number(m.SenderId));return <div key={m.MessageId} className={`chat-msg ${mine?'mine':'theirs'} ${m.IsPinned?'is-pinned':''}`} onPointerDown={e=>startPress(e,m)} onPointerUp={cancelPress} onPointerCancel={cancelPress} onPointerMove={cancelPress} onContextMenu={e=>{e.preventDefault();setMenuMessage(m);}}><div className="chat-bubble-wrap">{!mine&&tab==='group'&&<div className="chat-sender">{m.SenderName}</div>}<div className="chat-bubble">{m.IsPinned&&<div className="chat-pin"><SvgIcon name="pin" size={12}/>Pinned</div>}{m.ReplyBody&&<div className="chat-reply-quote"><strong>{m.ReplySenderName}</strong><span>{m.ReplyBody}</span></div>}<div>{request?request.text:m.Body}</div>{m.MessageType==='audio'&&m.AttachmentUrl?<audio controls preload="metadata" src={apiAssetUrl(m.AttachmentUrl)}/>:m.AttachmentUrl?<a className="chat-file" href={apiAssetUrl(m.AttachmentUrl)} target="_blank" rel="noreferrer"><SvgIcon name="receipt" size={18}/><span>{m.AttachmentName||'Open attachment'}</span></a>:null}{request&&!mine&&isAdmin&&<div className="chat-request-actions"><button onClick={()=>respondDeletion(request.requestId,'accept')}>Accept</button><button onClick={()=>respondDeletion(request.requestId,'decline')}>Decline</button></div>}<time>{new Date(m.CreatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>{!mine&&<button type="button" className="chat-message-report" onClick={()=>openReport('message',m)}><SvgIcon name="warning" size={13}/>Report message</button>}</div>{menuMessage?.MessageId===m.MessageId&&<div className={`chat-action-menu ${mine?'mine':''}`}><button onClick={()=>messageAction('reply',m)}><SvgIcon name="reply" size={18}/>Reply</button><button onClick={()=>messageAction('pin',m)}><SvgIcon name="pin" size={18}/>{m.IsPinned?'Unpin':'Pin'}</button>{!mine&&<button onClick={()=>openReport('message',m)}><SvgIcon name="warning" size={18}/>Report message</button>}{!mine&&<button onClick={()=>openReport('user',{UserId:m.SenderId,FirstName:m.SenderName,LastName:''})}><SvgIcon name="user" size={18}/>Report user</button>}{!mine&&<button className={blocked?'':'danger'} onClick={()=>toggleBlock(m)}><SvgIcon name="shield" size={18}/>{blocked?'Unblock user':'Block user'}</button>}{canDelete&&<button className="danger" onClick={()=>messageAction('delete',m)}><SvgIcon name="trash" size={18}/>Delete</button>}</div>}</div>;})}{!shown.length&&<div className="chat-empty">No messages yet. Start the conversation.</div>}<div ref={endRef}/></div>
        {replyTo&&<div className="chat-replying"><div><strong>Replying to {replyTo.SenderName}</strong><span>{replyTo.Body}</span></div><button onClick={()=>setReplyTo(null)}><SvgIcon name="x" size={17}/></button></div>}
        {!dmTo?.IsSystem&&<form onSubmit={send} className="chat-compose"><input ref={fileRef} type="file" hidden accept="image/*,application/pdf,audio/*" onChange={e=>uploadFile(e.target.files?.[0])}/><button type="button" className="chat-tool" onClick={()=>fileRef.current?.click()} disabled={busy} aria-label="Add attachment"><SvgIcon name="plus" size={24}/></button><input className="fi" value={body} onChange={e=>setBody(e.target.value)} placeholder={tab==='dm'?`Message ${dmTo?.FirstName||''}`:'Message the group'} disabled={busy}/><button type="button" className={`chat-tool ${recording?'recording':''}`} onClick={toggleRecording} disabled={busy} aria-label={recording?'Stop voice note':'Record voice note'}><SvgIcon name={recording?'stop':'microphone'} size={21}/></button><button className="chat-send" type="submit" disabled={busy||!body.trim()} aria-label="Send"><SvgIcon name="send" size={19}/></button></form>}
      </section>}
    </div>{menuMessage&&<button className="chat-menu-dismiss" onClick={()=>setMenuMessage(null)} aria-label="Close message menu"/>}
    {reportTarget&&<div className="chat-report-overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!moderationBusy)setReportTarget(null);}}><form className="chat-report-modal" role="dialog" aria-modal="true" aria-labelledby="chat-report-title" onSubmit={submitReport}><div className="chat-report-head"><div><h2 id="chat-report-title">Report {reportTarget.type==='message'?'message':'user'}</h2><p>Reports are confidential and reviewed for safety.</p></div><button type="button" onClick={()=>setReportTarget(null)} disabled={moderationBusy} aria-label="Close report"><SvgIcon name="x" size={20}/></button></div><label>Reason<select value={reportReason} onChange={event=>setReportReason(event.target.value)}>{reportReasons.map(reason=><option key={reason}>{reason}</option>)}</select></label><label>Additional details <span>(optional)</span><textarea maxLength="1000" rows="4" value={reportDetails} onChange={event=>setReportDetails(event.target.value)} placeholder="Tell us what happened."/></label><div className="chat-report-actions"><button type="button" onClick={()=>setReportTarget(null)} disabled={moderationBusy}>Cancel</button><button className="danger" type="submit" disabled={moderationBusy}>{moderationBusy?'Submitting…':'Submit report'}</button></div></form></div>}
  </div>;
}
