import { useEffect,useMemo,useState } from 'react';
import { useLocation,useNavigate } from 'react-router-dom';
import { apiGet,apiPost } from '../api/appClient.js';
import { useAuth } from '../context/AuthContext.jsx';
import SvgIcon from '../components/SvgIcon.jsx';
import { exportRows } from '../utils/adminExport.js';
import { copyText } from '../utils/nativeActions.js';

const CONFIG={
  '/system-admin':{endpoint:'overview',title:'System Overview',sub:'Platform health, activity and security monitoring'},
  '/system-admin/users':{endpoint:'users',title:'Users',sub:'Account, role and access monitoring'},
  '/system-admin/groups':{endpoint:'groups',title:'Groups',sub:'Group governance and activity monitoring'},
  '/system-admin/transactions':{endpoint:'transactions',title:'Transaction Monitoring',sub:'Read-only contribution and gateway oversight'},
  '/system-admin/security':{endpoint:'security',title:'Security',sub:'Authentication risks and privileged accounts'},
  '/system-admin/audit-logs':{endpoint:'audit-logs',title:'Audit Logs',sub:'Append-only administrative and security events'},
  '/system-admin/support':{endpoint:'support',title:'Support',sub:'Reports, disputes and support notifications'},
  '/system-admin/administrators':{endpoint:'administrators',title:'Administrators',sub:'Privileged account monitoring'},
  '/system-admin/settings':{endpoint:'settings',title:'Configuration Status',sub:'Read-only configuration status; secrets are never displayed'}
};
const display=v=>v===null||v===undefined||v===''?'—':typeof v==='boolean'?(v?'Yes':'No'):String(v).includes('T')&&!Number.isNaN(Date.parse(v))?new Date(v).toLocaleString():String(v);
const ADMIN_PERMISSIONS=['Manage users','Review groups','Suspend groups','Review transactions','Handle support tickets','Review security alerts','View audit logs','Export reports'];

export default function SystemAdmin(){
  const {user,logout,showToast}=useAuth(); const navigate=useNavigate();
  const location=useLocation(); const config=CONFIG[location.pathname]||CONFIG['/system-admin'];
  const [data,setData]=useState(null); const [error,setError]=useState(''); const [search,setSearch]=useState('');
  const [actionTarget,setActionTarget]=useState(null);const [action,setAction]=useState('');const [reason,setReason]=useState('');const [mfaCode,setMfaCode]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState('Member');const [until,setUntil]=useState('');const [busy,setBusy]=useState(false);
  const [priority,setPriority]=useState('Normal');
  const [recordTarget,setRecordTarget]=useState(null);
  const [createAdmin,setCreateAdmin]=useState(false);const [candidates,setCandidates]=useState([]);const [candidateId,setCandidateId]=useState('');const [permissions,setPermissions]=useState([]);
  const [menuRow,setMenuRow]=useState(null);const [menuPosition,setMenuPosition]=useState({top:0,left:0});const [selectedRow,setSelectedRow]=useState(null);const [selectedCell,setSelectedCell]=useState('');const [exportOpen,setExportOpen]=useState(false);
  const mfaReady=!!user?.MfaEnabled&&!!user?.MfaVerifiedAt;
  useEffect(()=>{if(!mfaReady){setData(null);setError('');return;}let active=true;setData(null);setError('');apiGet(`/system-admin/${config.endpoint}`).then(v=>active&&setData(v)).catch(e=>active&&setError(e.message));return()=>{active=false};},[config.endpoint,mfaReady]);
  const rows=useMemo(()=>{const all=data?.rows||[];const q=search.toLowerCase();return q?all.filter(row=>Object.values(row).some(v=>String(v??'').toLowerCase().includes(q))):all;},[data,search]);
  const columns=rows[0]?Object.keys(rows[0]):[];
  const firstFourColumns=columns.slice(0,4);
  const actionable=['users','groups','security','administrators','transactions','support','audit-logs'].includes(config.endpoint);
  const rowKey=(row,index=0)=>row.UserId||row.GroupId||row.TransactionId||row.AuditId||row.TicketId||row.AdminId||index;
  const openActions=(row,index,event)=>{const rect=event.currentTarget.getBoundingClientRect();setMenuPosition({top:Math.min(rect.bottom+5,window.innerHeight-370),left:Math.max(12,Math.min(rect.right-230,window.innerWidth-242))});setMenuRow(current=>current===rowKey(row,index)?null:rowKey(row,index));};
  const chooseAction=(row,value)=>{setMenuRow(null);setActionTarget(row);setAction(value);setReason('');setMfaCode('');setPassword('');setUntil('');setPriority(row.Priority||'Normal');};
  const choices=config.endpoint==='groups'?[['view','View group record'],['suspend','Suspend group'],['reactivate','Reactivate group'],['archive','Archive completed group'],['revoke-invites','Revoke invite codes'],['generate-invite','Generate invite code']]:config.endpoint==='transactions'?[['view','View full record'],['flag','Flag for investigation'],['note','Add internal note'],['resolve','Mark investigation resolved'],['false-positive','Mark false positive']]:config.endpoint==='support'?[['view','View support case'],['priority','Change priority'],['note','Add internal note'],['escalate','Escalate'],['resolve','Resolve'],['reopen','Reopen']]:config.endpoint==='audit-logs'?[['view','View audit details'],['copy-request','Copy request ID']]:[['view','View profile'],['verify-email','Verify email'],['activate','Activate or restore access'],['suspend','Suspend account'],['block','Block account'],['deactivate','Deactivate account'],['unlock','Unlock account'],['force-password-reset','Force password reset'],['revoke-sessions','Revoke all sessions'],['change-role','Change system role']].filter(([value])=>!actionTarget?.IsProtectedAccount||!['suspend','block','deactivate','change-role'].includes(value));
  const submitAction=async e=>{e.preventDefault();const id=actionTarget.GroupId||actionTarget.UserId||actionTarget.AdminId||actionTarget.TransactionId||actionTarget.TicketId;if(action==='view'){if((actionTarget.UserId||actionTarget.AdminId)&&config.endpoint!=='audit-logs')navigate(`/system-admin/users/${id}`);else setRecordTarget(actionTarget);setActionTarget(null);return;}if(action==='copy-request'){try{await copyText(String(actionTarget.RequestId||''));setError('');showToast('Request ID copied.');}catch{setError('Could not copy the request ID.');}setActionTarget(null);return;}setBusy(true);setError('');try{const section=config.endpoint==='administrators'||config.endpoint==='security'?'users':config.endpoint;const result=await apiPost(`/system-admin/${section}/${id}/action`,{action,reason,internalNote:reason,mfaCode,password,role,priority,until:until||null});setActionTarget(null);if(result?.inviteCode)setRecordTarget({...actionTarget,InviteCode:result.inviteCode});setData(await apiGet(`/system-admin/${config.endpoint}`));showToast('Administrative action completed.');}catch(ex){setError(ex.message);}finally{setBusy(false);}};
  const openCreateAdmin=async()=>{setError('');try{const result=await apiGet('/system-admin/administrator-candidates');setCandidates(result.rows||[]);setCandidateId('');setPermissions([]);setReason('');setMfaCode('');setPassword('');setCreateAdmin(true);}catch(ex){setError(ex.message);}};
  const submitCreateAdmin=async e=>{e.preventDefault();setBusy(true);setError('');try{await apiPost('/system-admin/administrators',{userId:Number(candidateId),permissions,reason,mfaCode,password});setCreateAdmin(false);setData(await apiGet('/system-admin/administrators'));showToast('Administrator appointed.');}catch(ex){setError(ex.message);}finally{setBusy(false);}};
  const runExport=async format=>{setExportOpen(false);try{await exportRows(rows,config.title,format);setError('');showToast(`${format.toUpperCase()} export ready.`);}catch(ex){setError(ex.message);}};
  if(!mfaReady) return <section className="sa-page"><div className="sa-mfa-warning-card"><div className="sa-mfa-icon"><SvgIcon name="shield" size={30}/></div><h1>Secure your Super Admin account</h1><p>Multi-factor authentication is required before you can access administrative data and controls.</p><div className="sa-mfa-actions"><button className="btn btn-g" onClick={()=>navigate('/system-admin/security/mfa/setup')}>Set up MFA now</button><button className="btn btn-gh" onClick={async()=>{await logout();navigate('/');}}>Sign out</button></div></div></section>;
  return <section className="sa-page" onClick={()=>{setMenuRow(null);setExportOpen(false)}}><div className="sa-title"><div><h1>{config.title}</h1><p>{config.sub}</p></div><div className="sa-title-actions">{config.endpoint==='administrators'&&<button className="btn btn-g" onClick={openCreateAdmin}>Create Admin</button>}<div className="sa-export" onClick={e=>e.stopPropagation()}><button className="btn btn-gh" onClick={()=>setExportOpen(v=>!v)}>Export ▾</button>{exportOpen&&<div className="sa-export-menu"><button onClick={()=>runExport('csv')}>CSV</button><button onClick={()=>runExport('excel')}>Excel</button><button onClick={()=>runExport('pdf')}>PDF</button></div>}</div><input aria-label="Search records" placeholder="Search this page…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
    {error&&<div className="err-msg">{error}</div>}
    {!data&&!error&&<div className="sa-loading">Loading protected system data…</div>}
    {data?.metrics&&<div className="sa-metrics">{Object.entries(data.metrics).map(([label,value])=><article key={label}><span>{label}</span><strong>{Number(value).toLocaleString()}</strong></article>)}</div>}
    {data?.status&&<div className="sa-panel"><h2>System status</h2><div className="sa-status-grid">{Object.entries(data.status).map(([label,value])=><div key={label}><span>{label}</span><strong>{display(value)}</strong></div>)}</div></div>}
    {data?.notice&&<div className="sa-notice">{data.notice}</div>}
    {data?.rows&&<div className="sa-table-wrap" onClick={e=>e.stopPropagation()}><table><thead><tr>{columns.map(c=><th key={c}>{c.replace(/([A-Z])/g,' $1').trim()}</th>)}{actionable&&<th>Actions</th>}</tr></thead><tbody>{rows.map((row,i)=>{const key=rowKey(row,i);const actionDisabled=config.endpoint==='security'&&row.SystemRole==='SuperAdmin';const available=choices.filter(([value])=>!row.IsProtectedAccount||!['suspend','block','deactivate','change-role'].includes(value));return <tr className={selectedRow===key?'is-selected':''} key={key} onClick={()=>{setSelectedRow(key);setSelectedCell('')}}>{columns.map(c=><td className={selectedCell===`${key}:${c}`?'is-selected-cell':''} key={c} onClick={e=>{e.stopPropagation();setSelectedRow(key);setSelectedCell(`${key}:${c}`)}}>{display(row[c])}</td>)}{actionable&&<td className="sa-actions-cell"><button className="btn btn-gh btn-sm" disabled={actionDisabled} title={actionDisabled?'SuperAdmin security controls are protected':'Open actions'} onClick={e=>{e.stopPropagation();if(!actionDisabled)openActions(row,i,e)}}>Actions ▾</button>{menuRow===key&&<div className="sa-row-menu" style={menuPosition}>{available.map(([value,label])=><button key={value} onClick={()=>chooseAction(row,value)}>{label}</button>)}</div>}</td>}</tr>})}{!rows.length&&<tr><td colSpan={Math.max(columns.length+(actionable?1:0),1)}>No records found.</td></tr>}</tbody></table></div>}
    {actionTarget&&<div className="modal-ov modal-ov-center open" onClick={e=>e.target===e.currentTarget&&!busy&&setActionTarget(null)}><form className="modal sa-action-modal" onSubmit={submitAction}><button type="button" className="modal-close" onClick={()=>setActionTarget(null)}><SvgIcon name="x" size={18}/></button><div className="modal-ttl">{choices.find(([value])=>value===action)?.[1]||'Controlled administrative action'}</div><div className="sa-action-target sa-action-target-columns">{firstFourColumns.map(column=><div key={column}><span>{column.replace(/([A-Z])/g,' $1').trim()}</span><strong>{display(actionTarget[column])}</strong></div>)}</div>{actionTarget.IsProtectedAccount&&<div className="sa-notice">Protected SuperAdmin: destructive controls are unavailable.</div>}{action&&action!=='view'&&action!=='copy-request'&&<><div className="fg"><label className="fl">WRITTEN REASON</label><textarea className="fta" required value={reason} onChange={e=>setReason(e.target.value)}/></div>{['suspend','block'].includes(action)&&<div className="fg"><label className="fl">END DATE (blank means indefinite)</label><input className="fi" type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)}/></div>}{action==='priority'&&<div className="fg"><label className="fl">NEW PRIORITY</label><select className="fs" value={priority} onChange={e=>setPriority(e.target.value)}><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></div>}{action==='change-role'&&<><div className="fg"><label className="fl">NEW ROLE</label><select className="fs" value={role} onChange={e=>setRole(e.target.value)}><option>Member</option><option>Admin</option></select></div><div className="fg"><label className="fl">SUPERADMIN PASSWORD</label><input className="fi" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></div></>}<div className="fg"><label className="fl">CURRENT MFA CODE</label><input className="fi" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/g,''))}/></div></>}<div className="sa-mfa-actions"><button type="button" className="btn btn-gh" onClick={()=>setActionTarget(null)}>Cancel</button><button className="btn btn-g" disabled={busy||!action}>{busy?'Applying…':action==='view'?'Open record':action==='copy-request'?'Copy request ID':'Confirm action'}</button></div></form></div>}
    {createAdmin&&<div className="modal-ov modal-ov-center open"><form className="modal sa-action-modal" onSubmit={submitCreateAdmin}><button type="button" className="modal-close" onClick={()=>setCreateAdmin(false)}><SvgIcon name="x" size={18}/></button><div className="modal-ttl">Create ordinary administrator</div><div className="sa-notice">Select a verified Member. This does not create a SuperAdmin and MFA remains optional for ordinary Admins.</div><div className="fg"><label className="fl">VERIFIED MEMBER</label><select className="fs" required value={candidateId} onChange={e=>setCandidateId(e.target.value)}><option value="">Select user</option>{candidates.map(c=><option key={c.UserId} value={c.UserId}>{c.Name} — {c.Email}</option>)}</select></div><fieldset className="sa-permissions"><legend>PERMISSIONS</legend>{ADMIN_PERMISSIONS.map(p=><label key={p}><input type="checkbox" checked={permissions.includes(p)} onChange={e=>setPermissions(v=>e.target.checked?[...v,p]:v.filter(x=>x!==p))}/>{p}</label>)}</fieldset><div className="fg"><label className="fl">APPOINTMENT REASON</label><textarea className="fta" required value={reason} onChange={e=>setReason(e.target.value)}/></div><div className="fg"><label className="fl">SUPERADMIN PASSWORD</label><input className="fi" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></div><div className="fg"><label className="fl">CURRENT MFA CODE</label><input className="fi" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/g,''))}/></div><div className="sa-mfa-actions"><button type="button" className="btn btn-gh" onClick={()=>setCreateAdmin(false)}>Cancel</button><button className="btn btn-g" disabled={busy||!candidateId||!permissions.length}>{busy?'Creating…':'Confirm appointment'}</button></div></form></div>}
    {recordTarget&&<div className="modal-ov modal-ov-center open" onClick={e=>e.target===e.currentTarget&&setRecordTarget(null)}><div className="modal sa-record-modal"><button type="button" className="modal-close" onClick={()=>setRecordTarget(null)}><SvgIcon name="x" size={18}/></button><div className="modal-ttl">{config.endpoint==='audit-logs'?'Audit log details':'Record details'}</div><div className="sa-record-grid">{Object.entries(recordTarget).map(([key,value])=><div key={key}><span>{key.replace(/([A-Z])/g,' $1')}</span><strong>{display(value)}</strong></div>)}</div></div></div>}
  </section>;
}
