import { Router } from 'express';
import fs from 'node:fs';
import { getPool, sql } from '../db.js';
import { chatUpload, requireAuth } from '../middleware.js';
import { sendPushToUser } from '../utils/push.js';
import { decryptRecords, encryptValue } from '../utils/fieldCrypto.js';
const r=Router();r.use(requireAuth);

const REPORT_REASONS=new Set(['Harassment or bullying','Hate speech','Threats or violence','Sexual content','Spam or scam','Impersonation','Other']);
async function sharedGroup(pool,gid,uid,other){const q=await pool.request().input('gid',sql.Int,gid).input('uid',sql.Int,uid).input('other',sql.Int,other).query(`SELECT g.GroupId FROM AjoGroups g JOIN GroupMembers a ON a.GroupId=g.GroupId AND a.UserId=@uid AND a.Status='Approved' JOIN GroupMembers b ON b.GroupId=g.GroupId AND b.UserId=@other AND b.Status='Approved' WHERE g.GroupId=@gid`);return q.recordset[0]||null;}

async function access(pool,gid,uid,rid,isPrivate){const q=await pool.request().input('gid',sql.Int,gid).input('uid',sql.Int,uid).input('rid',sql.Int,rid).query(`SELECT g.GroupMembersAnonymous,s.Role SenderRole,d.Role RecipientRole,CASE WHEN EXISTS(SELECT 1 FROM ChatUserBlocks b WHERE (b.BlockerUserId=@uid AND b.BlockedUserId=@rid) OR (b.BlockerUserId=@rid AND b.BlockedUserId=@uid)) THEN 1 ELSE 0 END IsBlocked FROM AjoGroups g LEFT JOIN GroupMembers s ON s.GroupId=g.GroupId AND s.UserId=@uid AND s.Status='Approved' LEFT JOIN GroupMembers d ON d.GroupId=g.GroupId AND d.UserId=@rid AND d.Status='Approved' WHERE g.GroupId=@gid`);const x=q.recordset[0];if(!x?.SenderRole)throw Object.assign(new Error('Group membership required'),{status:403});if(!isPrivate)return;if(!rid||rid===Number(uid)||!x.RecipientRole)throw Object.assign(new Error('Choose an approved private chat recipient'),{status:400});if(x.IsBlocked)throw Object.assign(new Error('Private messages are unavailable because one of you has blocked the other'),{status:403});if((x.GroupMembersAnonymous===1||x.GroupMembersAnonymous===true)&&x.SenderRole!=='Admin'&&x.RecipientRole!=='Admin')throw Object.assign(new Error('Private chat is limited to the group admin while anonymous mode is on'),{status:403});}
async function notify(pool,gid,sid,rid,isPrivate,type){const body=type==='audio'?'You have a new voice note.':type==='attachment'?'You have a new attachment.':`You have a new ${isPrivate?'private ':'group '}message.`;if(isPrivate){await pool.request().input('u',sql.Int,rid).input('g',sql.Int,gid).input('b',sql.NVarChar,body).query(`INSERT INTO Notifications(UserId,GroupId,Type,Title,Body) VALUES(@u,@g,'Chat','New Message',@b)`);return sendPushToUser(pool,sql,rid,{type:'Chat',title:'New Message',body,url:`/group/${gid}/chat`});}const users=await pool.request().input('g',sql.Int,gid).input('s',sql.Int,sid).query(`SELECT gm.UserId FROM GroupMembers gm JOIN Users u ON u.UserId=gm.UserId WHERE gm.GroupId=@g AND gm.Status='Approved' AND gm.UserId<>@s AND ISNULL(u.NotifChat,1)=1 AND NOT EXISTS(SELECT 1 FROM ChatUserBlocks b WHERE b.BlockerUserId=gm.UserId AND b.BlockedUserId=@s)`);await pool.request().input('g',sql.Int,gid).input('s',sql.Int,sid).input('b',sql.NVarChar,body).query(`INSERT INTO Notifications(UserId,GroupId,Type,Title,Body) SELECT gm.UserId,@g,'Chat','New Message',@b FROM GroupMembers gm JOIN Users u ON u.UserId=gm.UserId WHERE gm.GroupId=@g AND gm.Status='Approved' AND gm.UserId<>@s AND ISNULL(u.NotifChat,1)=1 AND NOT EXISTS(SELECT 1 FROM ChatUserBlocks block WHERE block.BlockerUserId=gm.UserId AND block.BlockedUserId=@s)`);await Promise.allSettled(users.recordset.map(x=>sendPushToUser(pool,sql,x.UserId,{type:'Chat',title:'New Message',body,url:`/group/${gid}/chat`})));}
async function create(req,res,next,file){try{const gid=Number(req.params.groupId),uid=req.user.userId,isPrivate=req.body.isPrivate===true||req.body.isPrivate==='true',rid=req.body.recipientId?Number(req.body.recipientId):null,reply=req.body.replyToMessageId?Number(req.body.replyToMessageId):null,text=String(req.body.body||'').trim();if(!text&&!file)return res.status(400).json({error:'Enter a message or add an attachment'});const pool=await getPool();await access(pool,gid,uid,rid,isPrivate);if(reply){const q=await pool.request().input('m',sql.BigInt,reply).input('g',sql.Int,gid).input('u',sql.Int,uid).query(`SELECT MessageId FROM Messages WHERE MessageId=@m AND GroupId=@g AND DeletedAt IS NULL AND (IsPrivate=0 OR SenderId=@u OR RecipientId=@u)`);if(!q.recordset.length)return res.status(400).json({error:'The replied message is unavailable'});}const mime=String(file?.mimetype||''),recordedAudio=String(file?.originalname||'').startsWith('voice-note-'),type=file?(mime.startsWith('audio/')||recordedAudio?'audio':'attachment'):'text',body=text||(type==='audio'?'Voice note':'Attachment');const q=await pool.request().input('g',sql.Int,gid).input('s',sql.Int,uid).input('r',sql.Int,isPrivate?rid:null).input('b',sql.NVarChar,encryptValue(body)).input('p',sql.Bit,isPrivate?1:0).input('url',sql.NVarChar,file?`chat:${file.filename}`:null).input('name',sql.NVarChar,file?.originalname||null).input('mime',sql.NVarChar,mime||null).input('type',sql.NVarChar,type).input('reply',sql.BigInt,reply).query(`INSERT INTO Messages(GroupId,SenderId,RecipientId,Body,IsPrivate,AttachmentUrl,AttachmentName,AttachmentMimeType,MessageType,ReplyToMessageId) OUTPUT INSERTED.* VALUES(@g,@s,@r,@b,@p,@url,@name,@mime,@type,@reply)`);const message=q.recordset[0];notify(pool,gid,uid,rid,isPrivate,type).catch(error=>console.error('Chat notification failed',error?.message||error));res.status(201).json({...message,Body:body,AttachmentUrl:file?`/api/private-files/message-${message.MessageId}`:null});}catch(e){if(file?.path)await fs.promises.unlink(file.path).catch(()=>{});if(e.status)return res.status(e.status).json({error:e.message});next(e);}}

r.get('/blocks',async(req,res,next)=>{try{const pool=await getPool(),q=await pool.request().input('uid',sql.Int,req.user.userId).query('SELECT BlockedUserId FROM ChatUserBlocks WHERE BlockerUserId=@uid ORDER BY CreatedAt DESC');res.json(q.recordset.map(x=>Number(x.BlockedUserId)));}catch(e){next(e);}});
r.post('/users/:userId/block',async(req,res,next)=>{try{const pool=await getPool(),uid=Number(req.user.userId),blocked=Number(req.params.userId),gid=Number(req.body.groupId);if(!blocked||blocked===uid||!gid)return res.status(400).json({error:'Choose another group member to block'});if(!await sharedGroup(pool,gid,uid,blocked))return res.status(403).json({error:'You can only block a member of this group'});await pool.request().input('uid',sql.Int,uid).input('blocked',sql.Int,blocked).query(`IF NOT EXISTS(SELECT 1 FROM ChatUserBlocks WHERE BlockerUserId=@uid AND BlockedUserId=@blocked) INSERT INTO ChatUserBlocks(BlockerUserId,BlockedUserId) VALUES(@uid,@blocked)`);res.json({blocked:true,userId:blocked});}catch(e){next(e);}});
r.delete('/users/:userId/block',async(req,res,next)=>{try{const pool=await getPool(),blocked=Number(req.params.userId);await pool.request().input('uid',sql.Int,req.user.userId).input('blocked',sql.Int,blocked).query('DELETE FROM ChatUserBlocks WHERE BlockerUserId=@uid AND BlockedUserId=@blocked');res.json({blocked:false,userId:blocked});}catch(e){next(e);}});
r.post('/users/:userId/report',async(req,res,next)=>{try{const pool=await getPool(),reporter=Number(req.user.userId),reported=Number(req.params.userId),gid=Number(req.body.groupId),reason=String(req.body.reason||'').trim(),details=String(req.body.details||'').trim().slice(0,1000);if(!reported||reported===reporter||!gid)return res.status(400).json({error:'Choose another group member to report'});if(!REPORT_REASONS.has(reason))return res.status(400).json({error:'Choose a valid report reason'});if(!await sharedGroup(pool,gid,reporter,reported))return res.status(403).json({error:'You can only report a member of this group'});try{await pool.request().input('reporter',sql.Int,reporter).input('reported',sql.Int,reported).input('gid',sql.Int,gid).input('reason',sql.NVarChar(100),reason).input('details',sql.NVarChar(1000),details||null).query(`INSERT INTO ChatReports(ReporterUserId,ReportedUserId,GroupId,MessageId,ReportType,Reason,Details) VALUES(@reporter,@reported,@gid,NULL,N'User',@reason,@details)`);}catch(error){if([2601,2627].includes(Number(error?.number)))return res.status(409).json({error:'You already have a pending report for this user in this group'});throw error;}res.status(201).json({reported:true});}catch(e){next(e);}});
r.post('/:messageId/report',async(req,res,next)=>{try{const pool=await getPool(),reporter=Number(req.user.userId),mid=Number(req.params.messageId),reason=String(req.body.reason||'').trim(),details=String(req.body.details||'').trim().slice(0,1000);if(!REPORT_REASONS.has(reason))return res.status(400).json({error:'Choose a valid report reason'});const q=await pool.request().input('mid',sql.BigInt,mid).input('uid',sql.Int,reporter).query(`SELECT m.MessageId,m.GroupId,m.SenderId FROM Messages m JOIN GroupMembers gm ON gm.GroupId=m.GroupId AND gm.UserId=@uid AND gm.Status='Approved' WHERE m.MessageId=@mid AND (m.IsPrivate=0 OR m.SenderId=@uid OR m.RecipientId=@uid)`),message=q.recordset[0];if(!message)return res.status(404).json({error:'Message not found'});if(Number(message.SenderId)===reporter)return res.status(400).json({error:'You cannot report your own message'});try{await pool.request().input('reporter',sql.Int,reporter).input('reported',sql.Int,message.SenderId).input('gid',sql.Int,message.GroupId).input('mid',sql.BigInt,message.MessageId).input('reason',sql.NVarChar(100),reason).input('details',sql.NVarChar(1000),details||null).query(`INSERT INTO ChatReports(ReporterUserId,ReportedUserId,GroupId,MessageId,ReportType,Reason,Details) VALUES(@reporter,@reported,@gid,@mid,N'Message',@reason,@details)`);}catch(error){if([2601,2627].includes(Number(error?.number)))return res.status(409).json({error:'You already reported this message and it is awaiting review'});throw error;}res.status(201).json({reported:true});}catch(e){next(e);}});

r.get('/group/:groupId',async(req,res,next)=>{try{const pool=await getPool(),gid=Number(req.params.groupId),uid=req.user.userId;const q=await pool.request().input('gid',sql.Int,gid).input('uid',sql.Int,uid).query(`SELECT m.*,reply.Body ReplyBody,COALESCE(reply.SenderNameOverride,ru.FirstName+' '+ru.LastName) ReplySenderName,CASE WHEN g.GroupMembersAnonymous=1 AND viewer.Role<>'Admin' AND sm.Role<>'Admin' AND m.SenderId<>@uid THEN 'Anonymous Member' ELSE COALESCE(m.SenderNameOverride,u.FirstName+' '+u.LastName) END SenderName,CASE WHEN g.GroupMembersAnonymous=1 AND viewer.Role<>'Admin' AND sm.Role<>'Admin' AND m.SenderId<>@uid THEN NULL ELSE u.ProfilePicture END ProfilePicture,CASE WHEN g.GroupMembersAnonymous=1 AND viewer.Role<>'Admin' AND sm.Role<>'Admin' AND m.SenderId<>@uid THEN '#2D5040' ELSE u.AvatarColor END AvatarColor FROM Messages m JOIN Users u ON u.UserId=m.SenderId JOIN AjoGroups g ON g.GroupId=m.GroupId JOIN GroupMembers viewer ON viewer.GroupId=m.GroupId AND viewer.UserId=@uid AND viewer.Status='Approved' LEFT JOIN GroupMembers sm ON sm.GroupId=m.GroupId AND sm.UserId=m.SenderId LEFT JOIN Messages reply ON reply.MessageId=m.ReplyToMessageId LEFT JOIN Users ru ON ru.UserId=reply.SenderId WHERE m.GroupId=@gid AND m.DeletedAt IS NULL AND (m.IsPrivate=0 OR m.SenderId=@uid OR m.RecipientId=@uid) AND (m.SenderId=@uid OR NOT EXISTS(SELECT 1 FROM ChatUserBlocks b WHERE b.BlockerUserId=@uid AND b.BlockedUserId=m.SenderId)) ORDER BY m.IsPinned DESC,m.CreatedAt ASC`);res.json(decryptRecords(q.recordset,['Body','ReplyBody']).map(x=>({...x,AttachmentUrl:x.AttachmentUrl?.startsWith('chat:')?`/api/private-files/message-${x.MessageId}`:x.AttachmentUrl})));}catch(e){next(e);}});
r.post('/group/:groupId',(req,res,next)=>create(req,res,next,null));
r.post('/group/:groupId/upload',chatUpload.single('attachment'),(req,res,next)=>create(req,res,next,req.file));
r.put('/:messageId/pin',async(req,res,next)=>{try{const pool=await getPool(),mid=Number(req.params.messageId),uid=req.user.userId,q=await pool.request().input('m',sql.BigInt,mid).input('u',sql.Int,uid).query(`SELECT m.IsPinned,m.SenderId,gm.Role FROM Messages m JOIN GroupMembers gm ON gm.GroupId=m.GroupId AND gm.UserId=@u AND gm.Status='Approved' WHERE m.MessageId=@m AND m.DeletedAt IS NULL`),x=q.recordset[0];if(!x)return res.status(404).json({error:'Message not found'});if(Number(x.SenderId)!==Number(uid)&&x.Role!=='Admin')return res.status(403).json({error:'Only the sender or group admin can pin this message'});const pinned=req.body.pinned!==undefined?!!req.body.pinned:!x.IsPinned;await pool.request().input('m',sql.BigInt,mid).input('p',sql.Bit,pinned).query('UPDATE Messages SET IsPinned=@p WHERE MessageId=@m');res.json({MessageId:mid,IsPinned:pinned});}catch(e){next(e);}});
r.delete('/:messageId',async(req,res,next)=>{try{const pool=await getPool(),q=await pool.request().input('m',sql.BigInt,Number(req.params.messageId)).input('u',sql.Int,req.user.userId).query(`UPDATE m SET DeletedAt=SYSUTCDATETIME() FROM Messages m JOIN GroupMembers gm ON gm.GroupId=m.GroupId AND gm.UserId=@u AND gm.Status='Approved' WHERE m.MessageId=@m AND m.DeletedAt IS NULL AND (m.SenderId=@u OR gm.Role='Admin')`);if(!q.rowsAffected[0])return res.status(403).json({error:'Only the sender or group admin can delete this message'});res.json({deleted:true});}catch(e){next(e);}});
export default r;
