import { Router } from 'express';
import { getPool, sql } from '../db.js';
import { rateLimit, requireAuth, requireMfa, requireSuperAdmin, requireVerifiedEmail } from '../middleware.js';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import { decryptMfaValue, encryptValue } from '../utils/fieldCrypto.js';
import { verifyTotp } from '../utils/mfa.js';

const r=Router();
r.use(requireAuth,requireVerifiedEmail,requireMfa,requireSuperAdmin);
const adminMutationLimit=rateLimit({windowMs:15*60*1000,max:20});
r.use((req,res,next)=>req.method==='GET'?next():adminMutationLimit(req,res,next));
const validId=value=>{const id=Number(value);return Number.isSafeInteger(id)&&id>0?id:null;};
const cleanText=(value,max)=>{const text=String(value||'').trim();return text&&text.length<=max?text:null;};

async function confirmAction(pool,req,{password=false}={}){
  const actor=(await pool.request().input('id',sql.Int,req.user.userId).query('SELECT * FROM dbo.Users WHERE UserId=@id AND IsActive=1 AND SystemRole=\'SuperAdmin\'')).recordset[0];
  if(!actor||!actor.MfaEnabled||!verifyTotp(decryptMfaValue(actor.MfaSecret),req.body?.mfaCode)) return {error:[401,'Current SuperAdmin MFA code is required']};
  if(password&&(!actor.PasswordHash||!await bcrypt.compare(String(req.body?.password||''),actor.PasswordHash))) return {error:[401,'SuperAdmin password confirmation failed']};
  if(!cleanText(req.body?.reason,500)) return {error:[400,'A written reason between 1 and 500 characters is required']};
  if(req.body?.internalNote&&String(req.body.internalNote).length>4000)return {error:[400,'Internal note must not exceed 4000 characters']};
  return {actor};
}
async function audit(pool,req,action,targetType,targetId,previousValue,newValue){await pool.request().input('actor',sql.Int,req.user.userId).input('action',sql.NVarChar,action).input('type',sql.NVarChar,targetType).input('target',sql.NVarChar,String(targetId)).input('before',sql.NVarChar(sql.MAX),JSON.stringify(previousValue||{})).input('after',sql.NVarChar(sql.MAX),JSON.stringify(newValue||{})).input('reason',sql.NVarChar,String(req.body.reason).trim()).input('note',sql.NVarChar(sql.MAX),req.body.internalNote||null).input('ip',sql.NVarChar,String(req.ip||'').slice(0,64)).query('INSERT dbo.AdminAuditLog(ActorUserId,Action,TargetType,TargetId,PreviousValue,NewValue,Reason,InternalNote,IpAddress) VALUES(@actor,@action,@type,@target,@before,@after,@reason,@note,@ip)');}

const scalar=async(pool,query)=>Number((await pool.request().query(query)).recordset[0]?.Value||0);

r.get('/overview',async(_req,res)=>{
  const pool=await getPool();
  const metrics=await Promise.all([
    ['Total users',scalar(pool,'SELECT COUNT(*) Value FROM dbo.Users')],
    ['Active users',scalar(pool,'SELECT COUNT(*) Value FROM dbo.Users WHERE IsActive=1')],
    ['Inactive users',scalar(pool,'SELECT COUNT(*) Value FROM dbo.Users WHERE IsActive=0')],
    ['Unverified users',scalar(pool,'SELECT COUNT(*) Value FROM dbo.Users WHERE IsEmailVerified=0')],
    ['Locked accounts',scalar(pool,'SELECT COUNT(*) Value FROM dbo.Users WHERE LockedUntil>SYSUTCDATETIME()')],
    ['New registrations today',scalar(pool,'SELECT COUNT(*) Value FROM dbo.Users WHERE CreatedAt>=CONVERT(date,SYSUTCDATETIME())')],
    ['Total groups',scalar(pool,'SELECT COUNT(*) Value FROM dbo.AjoGroups')],
    ['Active groups',scalar(pool,"SELECT COUNT(*) Value FROM dbo.AjoGroups WHERE Status='Active'")],
    ['Contributions recorded',scalar(pool,'SELECT COUNT(*) Value FROM dbo.Contributions')],
    ['Pending contributions',scalar(pool,"SELECT COUNT(*) Value FROM dbo.Contributions WHERE Status='Pending'")],
    ['Payouts recorded',scalar(pool,'SELECT COUNT(*) Value FROM dbo.Payouts')],
    ['Upcoming payouts',scalar(pool,"SELECT COUNT(*) Value FROM dbo.Payouts WHERE Status='Scheduled' AND ScheduledFor>=CONVERT(date,SYSUTCDATETIME())")],
    ['Failed logins recorded',scalar(pool,'SELECT ISNULL(SUM(FailedLoginCount),0) Value FROM dbo.Users')],
    ['Critical audit events',scalar(pool,"SELECT COUNT(*) Value FROM dbo.ActivityEvents WHERE Severity='critical'")]
  ]);
  res.json({metrics:Object.fromEntries(await Promise.all(metrics.map(async([k,v])=>[k,await v]))),status:{api:'Operational',database:'Connected',redis:'Monitored',email:process.env.SMTP_HOST?'Configured':'Not configured',paystack:process.env.PAYSTACK_SECRET_KEY?'Configured':'Disabled',fileStorage:'Protected',applicationVersion:'2.0.0'}});
});

r.get('/users',async(req,res)=>{
  const pool=await getPool(); const search=String(req.query.search||'').trim().slice(0,100);
  const result=await pool.request().input('search',sql.NVarChar,`%${search}%`).query(`
    SELECT TOP 100 u.UserId,u.FirstName+' '+u.LastName FullName,u.Email,u.SystemRole,u.IsProtectedAccount,
      u.IsEmailVerified,u.IsActive,u.AccountStatus,u.StatusUntil,u.MfaEnabled,u.FailedLoginCount,u.LockedUntil,u.LastLoginAt,u.LastLoginIp,u.CreatedAt,
      (SELECT COUNT(*) FROM dbo.GroupMembers gm WHERE gm.UserId=u.UserId) GroupCount
    FROM dbo.Users u
    WHERE @search='%%' OR u.Email LIKE @search OR u.FirstName LIKE @search OR u.LastName LIKE @search OR CONVERT(NVARCHAR,u.UserId) LIKE @search
    ORDER BY u.CreatedAt DESC`);
  res.json({rows:result.recordset});
});

r.get('/users/:id',async(req,res)=>{try{const pool=await getPool();const id=parseInt(req.params.id,10);if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Invalid user ID'});const user=(await pool.request().input('id',sql.Int,id).query(`SELECT UserId,FirstName,LastName,Email,ProfilePicture,SystemRole,IsProtectedAccount,IsEmailVerified,IsActive,AccountStatus,StatusUntil,FailedLoginCount,LockedUntil,MfaEnabled,TokenVersion,LastLoginAt,LastLoginIp,CreatedAt,UpdatedAt FROM dbo.Users WHERE UserId=@id`)).recordset[0];if(!user)return res.status(404).json({error:'User not found'});const [groupResult,auditResult]=await Promise.all([pool.request().input('id',sql.Int,id).query(`SELECT g.GroupId,g.GroupName,gm.Role,gm.Status,gm.SlotNumber,gm.JoinedAt FROM dbo.GroupMembers gm JOIN dbo.AjoGroups g ON g.GroupId=gm.GroupId WHERE gm.UserId=@id`),pool.request().input('id',sql.NVarChar,String(id)).query(`IF OBJECT_ID('dbo.AdminAuditLog') IS NULL SELECT TOP 0 CAST(NULL AS BIGINT) AuditId,CAST(NULL AS DATETIME2) CreatedAt,CAST(NULL AS NVARCHAR(80)) Action,CAST(NULL AS NVARCHAR(500)) Reason,CAST(NULL AS NVARCHAR(20)) Result ELSE SELECT TOP 100 AuditId,CreatedAt,Action,Reason,Result FROM dbo.AdminAuditLog WHERE TargetType='User' AND TargetId=@id ORDER BY CreatedAt DESC`)]);res.json({user,groups:groupResult.recordset,audit:auditResult.recordset});}catch(error){console.error('System user detail failed',error?.message);res.status(500).json({error:'Could not load the user record'});}});

r.post('/users/:id/action',async(req,res)=>{try{const pool=await getPool();const id=parseInt(req.params.id,10);const action=String(req.body?.action||'');const allowed=new Set(['verify-email','activate','suspend','block','deactivate','unlock','force-password-reset','revoke-sessions','change-role']);if(!allowed.has(action))return res.status(400).json({error:'Unsupported user action'});const confirmation=await confirmAction(pool,req,{password:action==='change-role'});if(confirmation.error)return res.status(confirmation.error[0]).json({error:confirmation.error[1]});const target=(await pool.request().input('id',sql.Int,id).query('SELECT UserId,Email,SystemRole,IsProtectedAccount,IsActive,AccountStatus,TokenVersion,LockedUntil FROM dbo.Users WHERE UserId=@id')).recordset[0];if(!target)return res.status(404).json({error:'User not found'});if(target.IsProtectedAccount&&['suspend','block','deactivate','change-role'].includes(action))return res.status(403).json({error:'Protected SuperAdmin cannot be suspended, blocked, deactivated or demoted',code:'PROTECTED_ACCOUNT'});let query='';const request=pool.request().input('id',sql.Int,id).input('reason',sql.NVarChar(sql.MAX),encryptValue(String(req.body.reason))).input('until',sql.DateTime2,req.body.until?new Date(req.body.until):null);
if(action==='verify-email')query='UPDATE dbo.Users SET IsEmailVerified=1,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id';
if(action==='activate')query="UPDATE dbo.Users SET IsActive=1,AccountStatus='Active',StatusReason=NULL,StatusUntil=NULL,TokenVersion=TokenVersion+1,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id";
if(action==='suspend')query="UPDATE dbo.Users SET IsActive=0,AccountStatus='Suspended',StatusReason=@reason,StatusUntil=@until,TokenVersion=TokenVersion+1,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id";
if(action==='block')query="UPDATE dbo.Users SET IsActive=0,AccountStatus='Blocked',StatusReason=@reason,StatusUntil=@until,TokenVersion=TokenVersion+1,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id";
if(action==='deactivate')query="UPDATE dbo.Users SET IsActive=0,AccountStatus='Deactivated',StatusReason=@reason,TokenVersion=TokenVersion+1,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id";
if(action==='unlock')query='UPDATE dbo.Users SET FailedLoginCount=0,LockedUntil=NULL,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id';
if(action==='force-password-reset')query='UPDATE dbo.Users SET MustResetPassword=1,TokenVersion=TokenVersion+1,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id';
if(action==='revoke-sessions')query='UPDATE dbo.Users SET TokenVersion=TokenVersion+1,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id';
if(action==='change-role'){const role=String(req.body?.role||'');if(!['Member','Admin'].includes(role))return res.status(400).json({error:'Role must be Member or Admin'});request.input('role',sql.NVarChar,role);query='UPDATE dbo.Users SET SystemRole=@role,TokenVersion=TokenVersion+1,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id';}
await request.query(query);const updated=(await pool.request().input('id',sql.Int,id).query('SELECT UserId,SystemRole,IsActive,AccountStatus,IsEmailVerified,LockedUntil,TokenVersion FROM dbo.Users WHERE UserId=@id')).recordset[0];await audit(pool,req,action,'User',id,target,updated);res.json({updated});}catch(error){console.error('System user action failed',error?.message);res.status(500).json({error:'Administrative action failed'});}});

r.post('/groups/:id/action',async(req,res)=>{try{const pool=await getPool();const id=parseInt(req.params.id,10);const action=String(req.body?.action||'');if(!['suspend','reactivate','archive','revoke-invites','generate-invite'].includes(action))return res.status(400).json({error:'Unsupported group action'});const confirmation=await confirmAction(pool,req);if(confirmation.error)return res.status(confirmation.error[0]).json({error:confirmation.error[1]});const before=(await pool.request().input('id',sql.Int,id).query('SELECT GroupId,Status FROM dbo.AjoGroups WHERE GroupId=@id')).recordset[0];if(!before)return res.status(404).json({error:'Group not found'});let inviteCode=null;if(action==='suspend')await pool.request().input('id',sql.Int,id).input('reason',sql.NVarChar(sql.MAX),encryptValue(req.body.reason)).query("UPDATE dbo.AjoGroups SET Status='Suspended',StatusReason=@reason WHERE GroupId=@id");if(action==='reactivate')await pool.request().input('id',sql.Int,id).query("UPDATE dbo.AjoGroups SET Status='Active',StatusReason=NULL,StatusUntil=NULL WHERE GroupId=@id");if(action==='archive')await pool.request().input('id',sql.Int,id).query("UPDATE dbo.AjoGroups SET Status='Archived' WHERE GroupId=@id AND Status='Completed'");if(action==='revoke-invites')await pool.request().input('id',sql.Int,id).query('UPDATE dbo.InviteCodes SET IsActive=0 WHERE GroupId=@id');if(action==='generate-invite'){inviteCode='ADMIN-'+crypto.randomBytes(9).toString('base64url').toUpperCase();await pool.request().input('id',sql.Int,id).input('uid',sql.Int,req.user.userId).input('code',sql.NVarChar,inviteCode).query('INSERT dbo.InviteCodes(GroupId,CreatedBy,Code) VALUES(@id,@uid,@code)');}const after=(await pool.request().input('id',sql.Int,id).query('SELECT GroupId,Status FROM dbo.AjoGroups WHERE GroupId=@id')).recordset[0];await audit(pool,req,action,'Group',id,before,after);res.json({updated:after,inviteCode});}catch(error){console.error('System group action failed',error?.message);res.status(500).json({error:'Administrative group action failed'});}});

r.get('/groups',async(_req,res)=>{const pool=await getPool();const q=await pool.request().query(`SELECT TOP 100 g.GroupId,g.GroupName,u.FirstName+' '+u.LastName Creator,g.ContributionAmount,g.CurrencyCode,g.Frequency,g.StartDate,g.Status,g.MaxMembers,g.CreatedAt,(SELECT COUNT(*) FROM dbo.GroupMembers m WHERE m.GroupId=g.GroupId AND m.Status='Approved') MemberCount FROM dbo.AjoGroups g JOIN dbo.Users u ON u.UserId=g.AdminUserId ORDER BY g.CreatedAt DESC`);res.json({rows:q.recordset});});
r.get('/transactions',async(_req,res)=>{const pool=await getPool();const q=await pool.request().query(`SELECT TOP 100 c.ContributionId TransactionId,g.GroupName,u.FirstName+' '+u.LastName Member,c.Amount,c.Method,c.Status,c.CycleNumber,c.CreatedAt,c.ReviewedAt ConfirmedAt FROM dbo.Contributions c JOIN dbo.AjoGroups g ON g.GroupId=c.GroupId JOIN dbo.Users u ON u.UserId=c.UserId ORDER BY c.CreatedAt DESC`);res.json({rows:q.recordset,notice:'Monitoring only. Sensitive references remain encrypted and are not returned.'});});
r.get('/security',async(_req,res)=>{const pool=await getPool();const q=await pool.request().query(`SELECT TOP 100 UserId,FirstName+' '+LastName [User],Email,SystemRole,FailedLoginCount,LockedUntil,MfaEnabled,LastLoginAt,LastLoginIp FROM dbo.Users WHERE FailedLoginCount>0 OR LockedUntil IS NOT NULL OR SystemRole IN ('Admin','SuperAdmin') ORDER BY ISNULL(LockedUntil,'19000101') DESC,FailedLoginCount DESC`);res.json({rows:q.recordset,notice:'Secrets, encryption keys and credentials are never exposed.'});});
r.get('/audit-logs',async(_req,res)=>{try{const pool=await getPool();const metadata=(await pool.request().query(`SELECT OBJECT_ID('dbo.AdminAuditLog') ObjectId,COL_LENGTH('dbo.AdminAuditLog','RequestId') RequestIdLength`)).recordset[0];if(!metadata?.ObjectId)return res.json({rows:[],notice:'No administrative audit log has been created yet.'});const requestColumn=metadata.RequestIdLength?'RequestId':'CAST(NULL AS UNIQUEIDENTIFIER) RequestId';const q=await pool.request().query(`SELECT TOP 200 AuditId,${requestColumn},CreatedAt,ActorUserId,Action,TargetType,TargetId,Reason,IpAddress FROM dbo.AdminAuditLog ORDER BY CreatedAt DESC`);res.json({rows:q.recordset,notice:'Audit records are read-only and append-only. They can be searched, inspected, copied and exported, but never changed or deleted.'});}catch(error){console.error('Audit log load failed',error?.message);res.status(500).json({error:'Could not load audit logs'});}});
r.get('/support',async(_req,res)=>{try{const pool=await getPool();const exists=(await pool.request().query("SELECT OBJECT_ID('dbo.SupportTickets') ObjectId")).recordset[0]?.ObjectId;if(!exists)return res.json({rows:[],notice:'Run migration 010 to enable support-ticket management.'});const q=await pool.request().query(`SELECT TOP 100 t.TicketId,t.TicketId TicketNumber,t.Subject,COALESCE(u.FirstName+' '+u.LastName,'Unlinked') [User],t.Category,t.Priority,t.Status,t.AssignedAdminId,t.CreatedAt,t.UpdatedAt FROM dbo.SupportTickets t LEFT JOIN dbo.Users u ON u.UserId=t.UserId ORDER BY t.UpdatedAt DESC`);res.json({rows:q.recordset});}catch(error){console.error('Support load failed',error?.message);res.status(500).json({error:'Could not load support cases'});}});
r.get('/administrators',async(_req,res)=>{try{const pool=await getPool();const hasPermissions=(await pool.request().query("SELECT OBJECT_ID('dbo.AdminPermissions') ObjectId")).recordset[0]?.ObjectId;const permissionColumn=hasPermissions?"(SELECT STRING_AGG(p.PermissionName,', ') FROM dbo.AdminPermissions p WHERE p.AdminUserId=u.UserId)":"CAST(NULL AS NVARCHAR(MAX))";const q=await pool.request().query(`SELECT u.UserId AdminId,u.FirstName+' '+u.LastName Name,u.Email,u.SystemRole,u.IsActive Status,u.IsProtectedAccount,u.MfaEnabled,u.LastLoginAt,u.CreatedAt,${permissionColumn} Permissions FROM dbo.Users u WHERE u.SystemRole IN ('Admin','SuperAdmin') ORDER BY u.SystemRole DESC,u.CreatedAt`);res.json({rows:q.recordset,notice:hasPermissions?'Protected SuperAdmin controls are intentionally unavailable.':'Run migration 010 to enable administrator permissions.'});}catch(error){console.error('Administrator load failed',error?.message);res.status(500).json({error:'Could not load administrators'});}});
r.get('/administrator-candidates',async(_req,res)=>{const pool=await getPool();const q=await pool.request().query("SELECT TOP 100 UserId,FirstName+' '+LastName Name,Email FROM dbo.Users WHERE IsActive=1 AND IsEmailVerified=1 AND SystemRole='Member' ORDER BY FirstName,LastName");res.json({rows:q.recordset});});
r.post('/administrators',async(req,res)=>{try{const pool=await getPool();const confirmation=await confirmAction(pool,req,{password:true});if(confirmation.error)return res.status(confirmation.error[0]).json({error:confirmation.error[1]});if(!confirmation.actor.IsProtectedAccount)return res.status(403).json({error:'Only the protected SuperAdmin can appoint administrators'});const id=parseInt(req.body?.userId,10);const permissions=[...new Set((Array.isArray(req.body?.permissions)?req.body.permissions:[]).map(String))];const allowed=new Set(['Manage users','Review groups','Suspend groups','Review transactions','Handle support tickets','Review security alerts','View audit logs','Export reports']);if(!permissions.length||permissions.some(x=>!allowed.has(x)))return res.status(400).json({error:'Choose valid administrator permissions'});const target=(await pool.request().input('id',sql.Int,id).query("SELECT UserId,SystemRole,IsProtectedAccount,IsActive,IsEmailVerified FROM dbo.Users WHERE UserId=@id")).recordset[0];if(!target||!target.IsActive||!target.IsEmailVerified||target.SystemRole!=='Member'||target.IsProtectedAccount)return res.status(409).json({error:'Select an eligible verified Member account'});const transaction=new sql.Transaction(pool);await transaction.begin();try{await new sql.Request(transaction).input('id',sql.Int,id).query("UPDATE dbo.Users SET SystemRole='Admin',TokenVersion=TokenVersion+1,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@id");for(const p of permissions)await new sql.Request(transaction).input('id',sql.Int,id).input('p',sql.NVarChar,p).input('by',sql.Int,req.user.userId).query('INSERT dbo.AdminPermissions(AdminUserId,PermissionName,GrantedBy) VALUES(@id,@p,@by)');await new sql.Request(transaction).input('id',sql.Int,id).input('body',sql.NVarChar,'You have been appointed as a My Ajo system administrator. MFA is optional for ordinary administrators at this time.').query("INSERT dbo.Notifications(UserId,Type,Title,Body) VALUES(@id,'AdminAppointment','Administrator appointment',@body)");await transaction.commit();}catch(e){await transaction.rollback();throw e;}await audit(pool,req,'create-admin','User',id,target,{SystemRole:'Admin',permissions});res.status(201).json({created:true});}catch(error){console.error('Create admin failed',error?.message);res.status(500).json({error:'Could not appoint administrator'});}});

r.post('/transactions/:id/action',async(req,res)=>{try{const pool=await getPool();const action=String(req.body?.action||'');if(!['flag','note','resolve','false-positive'].includes(action))return res.status(400).json({error:'Unsupported investigation action'});const confirmation=await confirmAction(pool,req);if(confirmation.error)return res.status(confirmation.error[0]).json({error:confirmation.error[1]});const id=parseInt(req.params.id,10);const existing=(await pool.request().input('id',sql.Int,id).query('SELECT TOP 1 * FROM dbo.TransactionInvestigations WHERE ContributionId=@id ORDER BY CreatedAt DESC')).recordset[0];if(!existing)await pool.request().input('id',sql.Int,id).input('by',sql.Int,req.user.userId).input('note',sql.NVarChar(sql.MAX),req.body.internalNote||null).query("INSERT dbo.TransactionInvestigations(ContributionId,Status,InternalNote,CreatedBy) VALUES(@id,'Open',@note,@by)");else await pool.request().input('iid',sql.BigInt,existing.InvestigationId).input('note',sql.NVarChar(sql.MAX),req.body.internalNote||existing.InternalNote).input('status',sql.NVarChar,action==='resolve'?'Resolved':action==='false-positive'?'FalsePositive':action==='note'?existing.Status:'Investigating').query('UPDATE dbo.TransactionInvestigations SET Status=@status,InternalNote=@note,ResolvedAt=CASE WHEN @status IN(\'Resolved\',\'FalsePositive\') THEN SYSUTCDATETIME() ELSE ResolvedAt END WHERE InvestigationId=@iid');await audit(pool,req,action,'Contribution',id,existing,{status:action});res.json({updated:true});}catch(error){console.error('Investigation action failed',error?.message);res.status(500).json({error:'Investigation action failed'});}});

r.post('/support/:id/action',async(req,res)=>{try{const pool=await getPool();const action=String(req.body?.action||'');const statuses={escalate:'Escalated',resolve:'Resolved',reopen:'Open'};if(!['priority','note',...Object.keys(statuses)].includes(action))return res.status(400).json({error:'Unsupported support action'});const confirmation=await confirmAction(pool,req);if(confirmation.error)return res.status(confirmation.error[0]).json({error:confirmation.error[1]});const id=parseInt(req.params.id,10);const before=(await pool.request().input('id',sql.BigInt,id).query('SELECT * FROM dbo.SupportTickets WHERE TicketId=@id')).recordset[0];if(!before)return res.status(404).json({error:'Support ticket not found'});const nextStatus=statuses[action]||before.Status;const allowedPriorities=new Set(['Low','Normal','High','Urgent']);const nextPriority=action==='priority'?String(req.body?.priority||''):before.Priority;if(!allowedPriorities.has(nextPriority))return res.status(400).json({error:'Choose a valid ticket priority'});await pool.request().input('id',sql.BigInt,id).input('status',sql.NVarChar,nextStatus).input('note',sql.NVarChar(sql.MAX),req.body.internalNote||null).input('priority',sql.NVarChar,nextPriority).query('UPDATE dbo.SupportTickets SET Status=@status,InternalNote=COALESCE(@note,InternalNote),Priority=@priority,UpdatedAt=SYSUTCDATETIME() WHERE TicketId=@id');await audit(pool,req,action,'SupportTicket',id,before,{Status:nextStatus,Priority:nextPriority});res.json({updated:true});}catch(error){console.error('Support action failed',error?.message);res.status(500).json({error:'Support action failed'});}});
r.get('/settings',async(_req,res)=>res.json({rows:[{Setting:'Application name',Value:'My Ajo'},{Setting:'Default currency',Value:'NGN'},{Setting:'Dates stored as',Value:'UTC'},{Setting:'Verified members create groups',Value:'Enabled'},{Setting:'Minimum password length',Value:'12'},{Setting:'Login attempt limit',Value:'5'},{Setting:'Temporary lockout',Value:'15 minutes'},{Setting:'Mandatory MFA',Value:'SuperAdmin only'},{Setting:'Optional MFA',Value:'Members and Admins'},{Setting:'Paystack secret',Value:process.env.PAYSTACK_SECRET_KEY?'Configured':'Not configured'},{Setting:'MFA encryption',Value:process.env.MFA_ENCRYPTION_KEY?'Configured':'Not configured'}],notice:'Secret values and server command execution are never available here.'}));

export default r;
